### PR TITLE
Closes #27

### LINKED ISSUE #27: https - Self Signed Certs
When I try to test a connection over https that uses a self-signed cert, I get the following error:

    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: self signed certificate in certificate chain
        at Error (native)
        at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
        at TLSSocket.emit (events.js:104:17)
        at TLSSocket._finishInit (_tls_wrap.js:460:8)

Would it be possible to add support for unsigned ssl certs?

I have done this previously be using [https.request()](https://nodejs.org/api/https.html#https_https_request_options_callback) with the following two flags set:

    requestCert: true
    rejectUnauthorized: false
    
Reference:
https://nodejs.org/api/https.html#https_https_request_options_callback
https://nodejs.org/api/tls.html

### PR DESCRIPTION
**Pull request by mohdhallal**

### CODE REVIEW

**Comment by mohdhallal** [comment]
yoow @unlucio please take a look at this.

I know pinging @odino now might not be the best course of action :P

File: src/index.js [hunk 1]
```diff
@@ -9,13 +10,25 @@ var shisha = {
      * @param data
      * @param locals
      * @param callback
+     * @param capath
      */
-    smoke: function (data, locals, callback) {
+    smoke: function (data, locals, callback, capath) {
```
Comment (cirpo) [inline src/index.js]: wouldn't be better to have it camelCase: caPath?

File: src/index.js [hunk 2]
```diff
@@ -9,13 +10,25 @@ var shisha = {
...
         var report = [];
-        
-        if (!callback) {
-            callback = locals;
-            locals = {};
+
+        if (!capath)
+        {
+            if (!callback)
```
Comment (cirpo) [inline src/index.js]: ypeof callback != 'function' should be enough

File: src/index.js [hunk 3]
```diff
@@ -9,13 +10,25 @@ var shisha = {
...
      */
-    smoke: function (data, locals, callback) {
+    smoke: function (data, locals, callback, capath) {
         var report = [];
-        
-        if (!callback) {
-            callback = locals;
-            locals = {};
+
+        if (!capath)
```
Comment (cirpo) [inline src/index.js]: @mohdhallal could you please explain the logic between line 18 and 31? Are we shifting arguments?

File: bin/shisha.js [hunk 4]
```diff
@@ -35,7 +36,7 @@ try {
         });
 
         process.exit(exitStatus);
-});
+    }, ca);
 } catch (e) {
     console.log(e.message.red);
 }
```
Comment (cirpo) [inline bin/shisha.js]: missing blank line

File: test/shisha.spec.js [hunk 5]
```diff
@@ -129,4 +131,46 @@ describe('Shisha: smoke tests',function(){
...
+
+    it('should be able to connect to an HTTPS server with a self signed certificate without locals', function(done) {
+        shisha.smoke(path.join('test', 'validshishafile', '.smokehttpswolocals'), function (output) {
+            for (var url in output) {
+                assert.equal(output[url].result, true);
+            }
+            done();
+        }, './test/certs/cert.pem');
+    });
 });
```
Comment (cirpo) [inline test/shisha.spec.js]: missing blank line

File: src/index.js [hunk 6]
```diff
@@ -9,13 +10,25 @@ var shisha = {
...
+        {
+            if (!callback)
+            {
```
Comment (cirpo) [inline src/index.js]: curly braces should stay on the same line

File: src/index.js (hunk 1 above)
Comment (unlucio) [inline src/index.js]: options.locals
options.acPath

File: src/index.js (hunk 6 above)
Comment (unlucio) [inline src/index.js]: Is this php? Or perhaps per? :D

File: src/index.js (hunk 3 above)
Comment (unlucio) [inline src/index.js]: Optional locals and mandatory callback resolution. It's OK

File: src/index.js (hunk 1 above)
Comment (cirpo) [inline src/index.js]: `ca` is optional and it's an argument, like `locals`. The suggestion could be to have a new `options` object and `locals` as its attribute, eg:
```js
var options = {
   locals: {...},
   ca: ...
} 
```
and the smoke signature will change into:

```js
smoke: function (data, options, callback)
```

wdyt? @unlucio ?

Comment (mohdhallal) [inline src/index.js]: Indeed that makes sense, however, I did not wish to break BC at this point. I hope it can be refactored to an options object in a later major release

File: bin/shisha.js (hunk 4 above)
Comment (mohdhallal) [inline bin/shisha.js]: Ok

File: test/shisha.spec.js (hunk 5 above)
Comment (mohdhallal) [inline test/shisha.spec.js]: Ok

File: src/index.js (hunk 6 above)
Comment (mohdhallal) [inline src/index.js]: looool, PHPing

File: src/index.js (hunk 1 above)
Comment (cirpo) [inline src/index.js]: ok, are you going to send the PR and lets bump the release?

**Comment by mohdhallal** [comment]
@cirpo all good!

File: src/index.js [hunk 7]
```diff
@@ -9,17 +10,26 @@ var shisha = {
...
+            if (!callback) {
+                callback = locals;
+                locals = {};
+            }
+
+            if (typeof callback != 'function') {
+                options = callback;
+                callback = locals;
+                locals = {};
+            }
```
Comment (odino) [inline src/index.js]: Ah, JavaScript :)

File: src/index.js [hunk 8]
```diff
@@ -44,9 +54,14 @@ var shisha = {
         };
         
         var testResource = function (resource) {
-            var options = url.parse(resource.url(locals));
-            options.agent = false;
-            http.request(options, addToReport(resource.url, resource.status)).end();
+            var Requestoptions = url.parse(resource.url(locals));
```
Comment (odino) [inline src/index.js]: should be requestOptions, but then everything else looks fine to me!

**Comment by mohdhallal** [comment]
@odino @cirpo all good here!

**Comment by odino** [comment]
Thanks :)
